---
driver:
  name: docker
  hostname: apache.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: apache
  grains:
    noservices: False
  state_top:
    base:
      "*":
        - apache
  pillars:
    top.sls:
      base:
        "*":
          - apache

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: apache_server_php5
    provisioner:
      pillars-from-files:
        apache.sls: tests/pillar/apache_server_php5.sls

  - name: apache_server_php7
    provisioner:
      pillars-from-files:
        apache.sls: tests/pillar/apache_server_php7.sls

  - name: apache_server_php7_ssl
    provisioner:
      pillars-from-files:
        apache.sls: tests/pillar/apache_server_php7_ssl.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
